name: Build on Push
on:
  push:
    branches: [build] 

jobs:
    pre-release:
      name: Pre Release
      runs-on: macOS-latest
      steps:
        - name: Checkout the repository
          uses: actions/checkout@v2
        - name: Generate build files
        - uses: marvinpinto/action-automatic-releases@latest
          with:
            repo_token: '${{ secrets.GITHUB_TOKEN }}'
            automatic_release_tag: spotify-lite-go-${{ steps.date.outputs.date }}
            prerelease: true
            title: "Spotify Lite Go Build ${{ steps.date.outputs.date }}"
            files: ./*.app
