name: Package Mac
on:
  create:
    tags: '*'

jobs:
  pre-release:
    name: Pre Release
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest]
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch_depth: 0

      - name: Generate Change Log Linux
        if: matrix.os == 'ubuntu-latest'
        run: sh changelog_linux.sh

      - name: Generate Change Log Mac
        if: matrix.os == 'macOS-latest'
        run: sh changelog.sh

      - name: Install Linux Dev Deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install xorg-dev libgl1-mesa-dev

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
          fi
          go get fyne.io/fyne/cmd/fyne

      - name: Package App Mac
        if: matrix.os == 'macOS-latest'
        run: |
          fyne package -os darwin -name "Spotify Lite"
          mkdir -p dist 
          mv "Spotify Lite.app" dist/
          cd dist
          npx create-dmg Spotify\ Lite.app | echo "done"
          rm -rf "Spotify Lite.app"

      - name: Package App Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          fyne package -os linux -name "Spotify Lite"
          mkdir -p dist 
          mv "Spotify Lite.tar.gz" dist/

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.txt
          files: 'dist/**'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
